name: qycli-php
base: core20
adopt-info: qycli-php
summary: PHP for qycli
description: "PHP for the qycli LEMP stack"

grade: devel
confinement: devmode

architectures:
  - build-on: amd64

parts:
  qycli-php:
    plugin: autotools
    override-pull: |
      curl -s https://www.php.net/downloads.php | tac | tac | grep '<h3 id="v.*"' | tr -d '<h3 id="vclassttle>' > phpVersions

      php_new_stable=$(cat phpVersions | sed -n 1p)
      php_old_stable=$(cat phpVersions | sed -n 2p)
      php_security_only=$(cat phpVersions | sed -n 3p)

      snapcraftctl set-version "${php_new_stable}+${php_old_stable}+${php_security_only}"

      # Downloading supported PHP versions
      wget -qO php_new_stable.tar.xz https://www.php.net/distributions/php-${php_new_stable}.tar.xz

      # Unpacking the PHP versions
      mkdir $SNAPCRAFT_PROJECT_DIR/php_new_stable
      tar -xf php_new_stable.tar.xz --strip-components=1 -C $SNAPCRAFT_PROJECT_DIR/php_new_stable/

      # Downloading external extensions
      wget -qO imagick-latest.tgz https://pecl.php.net/get/imagick
      mkdir $SNAPCRAFT_PROJECT_DIR/php_new_stable/ext/imagick
      tar -zxf imagick-latest.tgz --strip-components=1 -C $SNAPCRAFT_PROJECT_DIR/php_new_stable/ext/imagick/

      # Deleting configure script for extensions to be compiled also
      cd $SNAPCRAFT_PROJECT_DIR/php_new_stable/
      rm configure

      snapcraftctl pull

    source: $SNAPCRAFT_PROJECT_DIR/php_new_stable/
    source-type: local
    build-packages:
      - software-properties-common
      - curl
      - wget
      - tar
      - php-pear
      - libxml2-dev
      - pkg-config
      - libssl-dev
      - libcurl4-openssl-dev
      - libpng-dev
      - libjpeg8-dev
      - libwebp-dev
      - ImageMagick-dev
      - libzip-dev
      - libargon2-0-dev
      - libonig-dev
      - libsodium-dev
    autotools-configure-parameters:
      - --prefix=/usr/bin/php/
      - --enable-fpm
      - --disable-cgi
      - --disable-phpdbg
      - --without-sqlite3
      - --without-pdo-sqlite
      - --with-mysqli
      - --with-curl
      - --enable-exif
      - --with-imagick
      - --enable-mbstring
      - --with-openssl
      - --with-zip
      - --enable-bcmath
      - --enable-gd
      - --with-jpeg
      - --with-png
      - --with-webp
      - --enable-intl
      - --with-sodium
      - --with-zlib
      - --enable-soap
