name: qycli-php
base: core20
adopt-info: qycli-php-sources
summary: PHP for qycli
description: "PHP for the qycli LEMP stack"

grade: devel
confinement: devmode

architectures:
  - build-on: amd64

apps:
  php-versions:
    command: cat phpVersions

parts:
  qycli-php-sources:
    plugin: dump
    override-pull: |
      curl -s https://www.php.net/downloads.php | tac | tac | grep '<h3 id="v.*"' | tr -d '<h3 id="vclassttle>' > phpVersions

      php_new_stable=$(cat phpVersions | sed -n 1p)
      php_old_stable=$(cat phpVersions | sed -n 2p)
      php_security_only=$(cat phpVersions | sed -n 3p)

      snapcraftctl set-version "${php_new_stable}+${php_old_stable}+${php_security_only}"

      # Downloading supported PHP versions
      wget -qO php_new_stable.tar.xz https://www.php.net/distributions/php-${php_new_stable}.tar.xz
      wget -qO php_old_stable.tar.xz https://www.php.net/distributions/php-${php_old_stable}.tar.xz
      wget -qO php_security_only.tar.xz https://www.php.net/distributions/php-${php_security_only}.tar.xz

      # Unpacking the PHP versions
      mkdir php_new_stable
      tar -xf php_new_stable.tar.xz --strip-components=1 -C php_new_stable/
      mkdir php_old_stable
      tar -xf php_old_stable.tar.xz --strip-components=1 -C php_old_stable/
      mkdir php_security_only
      tar -xf php_security_only.tar.xz --strip-components=1 -C php_security_only/

      # Downloading external extensions
      wget -qO imagick-latest.tgz https://pecl.php.net/get/imagick
      mkdir php_new_stable/ext/imagick
      tar -zxf imagick-latest.tgz --strip-components=1 -C php_new_stable/ext/imagick/
      mkdir php_old_stable/ext/imagick
      tar -zxf imagick-latest.tgz --strip-components=1 -C php_old_stable/ext/imagick/
      mkdir php_security_only/ext/imagick
      tar -zxf imagick-latest.tgz --strip-components=1 -C php_security_only/ext/imagick/

      #chmod +x $SNAPCRAFT_PROJECT_DIR/php-sources-pull
      #$SNAPCRAFT_PROJECT_DIR/php-sources-pull
    source: phpVersions

  qycli-php:
    after: qycli-php-sources
    plugin: autotools
    source: php_new_stable/
    build-packages:
      - libxml2-dev
      - libcurl4-openssl-dev
      - libpng-dev
      - libjpeg8-dev
      - libzip-dev
      - libargon2-0-dev
      - libonig-dev
    autotools-configure-parameters:
      - --enable-fpm
      - --disable-cgi
      - --disable-phpdbg
      - --without-sqlite3
      - --without-pdo-sqlite
      - --with-mysqli
      - --with-curl
      - --enable-exif
      - --with-imagick
      - --enable-mbstring
      - --with-openssl
      - --with-zip
      - --enable-bcmath
      - --with-gd
      - --enable-intl
      - --with-sodium
      - --with-zlib
      - --enable-soap
